
import java.sql.*;
import javax.swing.*;

public class JfrmSubjects extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;
    
    public JfrmSubjects() {
        initComponents();
        DoConnect();
    }
    
    private void DoConnect(){
        try{
            
            String host = "jdbc:mysql://localhost:3306/student_grading_system";
            String user = "root";
            String pass = "";
            con = DriverManager.getConnection(host,user,pass);
            
            stmt = con.createStatement();
            String sql = "Select * from subjects";
            rs = stmt.executeQuery(sql);
            
            rs.next();
            
            int id_col = rs.getInt("idnum");
            String id = Integer.toString(id_col);
            String lastname = rs.getString("lastname");
            String firstname = rs.getString("firstname");
            String middlename = rs.getString("middlename");
            String subject = rs.getString("subject");
            int attend_col = rs.getInt("attendance");
            String attend = Integer.toString(attend_col);
            int part_col = rs.getInt("participation");
            String part = Integer.toString(part_col);
            int proj_col = rs.getInt("project");
            String proj = Integer.toString(proj_col);
            int quiz_col = rs.getInt("quiz");
            String quiz = Integer.toString(quiz_col);
            int attit_col = rs.getInt("attitude");
            String attitude = Integer.toString(attit_col);
            int final_col = rs.getInt("finalexam");
            String exam = Integer.toString(final_col);
            int grade_col = rs.getInt("finalgrade");
            String grade = Integer.toString(grade_col);
            
                
        }
         catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "error");
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcboxSubj = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtAtt = new javax.swing.JTextField();
        jtxtFinal = new javax.swing.JTextField();
        jtxtPart = new javax.swing.JTextField();
        jtxtProj = new javax.swing.JTextField();
        jtxtQuiz = new javax.swing.JTextField();
        jtxtAttit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtGrade = new javax.swing.JTextField();
        jtxtSearch = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtLastname = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtMidname = new javax.swing.JTextField();
        jtxtIdnum = new javax.swing.JTextField();
        jbtnSavesubj = new javax.swing.JButton();
        jbtnSearchsubj = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnScore = new javax.swing.JButton();
        jbtnNew = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 57, 139));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subject");

        jcboxSubj.setBackground(new java.awt.Color(57, 57, 139));
        jcboxSubj.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jcboxSubj.setForeground(new java.awt.Color(255, 255, 255));
        jcboxSubj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Math", "Filipino", "Computer Programming 1", "Data Structure" }));
        jcboxSubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxSubjActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attendance");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quiz");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Participation");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Project");

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Final Exam");

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Attitude");

        jtxtAtt.setBackground(new java.awt.Color(57, 57, 139));
        jtxtAtt.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtAtt.setForeground(new java.awt.Color(0, 204, 0));
        jtxtAtt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtAtt.setBorder(null);
        jtxtAtt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAttActionPerformed(evt);
            }
        });

        jtxtFinal.setBackground(new java.awt.Color(57, 57, 139));
        jtxtFinal.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtFinal.setForeground(new java.awt.Color(0, 204, 0));
        jtxtFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFinal.setBorder(null);

        jtxtPart.setBackground(new java.awt.Color(57, 57, 139));
        jtxtPart.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtPart.setForeground(new java.awt.Color(0, 204, 0));
        jtxtPart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPart.setBorder(null);

        jtxtProj.setBackground(new java.awt.Color(57, 57, 139));
        jtxtProj.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtProj.setForeground(new java.awt.Color(0, 204, 0));
        jtxtProj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtProj.setBorder(null);

        jtxtQuiz.setBackground(new java.awt.Color(57, 57, 139));
        jtxtQuiz.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtQuiz.setForeground(new java.awt.Color(0, 204, 0));
        jtxtQuiz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQuiz.setBorder(null);
        jtxtQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuizActionPerformed(evt);
            }
        });

        jtxtAttit.setBackground(new java.awt.Color(57, 57, 139));
        jtxtAttit.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtAttit.setForeground(new java.awt.Color(0, 204, 0));
        jtxtAttit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtAttit.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Final Grade");

        jtxtGrade.setEditable(false);
        jtxtGrade.setBackground(new java.awt.Color(57, 57, 139));
        jtxtGrade.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtGrade.setForeground(new java.awt.Color(0, 204, 0));
        jtxtGrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGrade.setBorder(null);
        jtxtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGradeActionPerformed(evt);
            }
        });

        jtxtSearch.setBackground(new java.awt.Color(57, 57, 139));
        jtxtSearch.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtSearch.setForeground(new java.awt.Color(255, 255, 255));
        jtxtSearch.setBorder(null);
        jtxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Number :");

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Last Name :");

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First Name :");

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Middle Name :");

        jtxtLastname.setEditable(false);
        jtxtLastname.setBackground(new java.awt.Color(57, 57, 139));
        jtxtLastname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtLastname.setForeground(new java.awt.Color(0, 204, 0));
        jtxtLastname.setBorder(null);
        jtxtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastnameActionPerformed(evt);
            }
        });

        jtxtFirstname.setEditable(false);
        jtxtFirstname.setBackground(new java.awt.Color(57, 57, 139));
        jtxtFirstname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtFirstname.setForeground(new java.awt.Color(0, 204, 0));
        jtxtFirstname.setBorder(null);

        jtxtMidname.setEditable(false);
        jtxtMidname.setBackground(new java.awt.Color(57, 57, 139));
        jtxtMidname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtMidname.setForeground(new java.awt.Color(0, 204, 0));
        jtxtMidname.setBorder(null);

        jtxtIdnum.setEditable(false);
        jtxtIdnum.setBackground(new java.awt.Color(57, 57, 139));
        jtxtIdnum.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jtxtIdnum.setForeground(new java.awt.Color(0, 204, 0));
        jtxtIdnum.setBorder(null);
        jtxtIdnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdnumActionPerformed(evt);
            }
        });

        jbtnSavesubj.setBackground(new java.awt.Color(19, 31, 160));
        jbtnSavesubj.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtnSavesubj.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSavesubj.setText("Save");
        jbtnSavesubj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnSavesubj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSavesubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSavesubjActionPerformed(evt);
            }
        });

        jbtnSearchsubj.setBackground(new java.awt.Color(19, 31, 160));
        jbtnSearchsubj.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtnSearchsubj.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSearchsubj.setText("Search");
        jbtnSearchsubj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnSearchsubj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSearchsubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchsubjActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(19, 31, 160));
        jbtnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBack.setText("Back");
        jbtnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jbtnScore.setBackground(new java.awt.Color(19, 31, 160));
        jbtnScore.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtnScore.setForeground(new java.awt.Color(255, 255, 255));
        jbtnScore.setText("Score");
        jbtnScore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnScoreActionPerformed(evt);
            }
        });

        jbtnNew.setBackground(new java.awt.Color(19, 31, 160));
        jbtnNew.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jbtnNew.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNew.setText("New");
        jbtnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbtnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxtIdnum, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnSavesubj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSearchsubj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(jtxtMidname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxtProj, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(23, 221, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtAttit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addGap(62, 62, 62))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel3)
                                                            .addGap(12, 12, 12))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(1, 1, 1))
                                                        .addComponent(jtxtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jtxtFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(1, 1, 1))))
                                                .addGap(21, 21, 21))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnScore, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(52, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtPart, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcboxSubj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(34, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcboxSubj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtProj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel3))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtAttit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnNew, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnScore, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtSearch))
                .addGap(7, 7, 7)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSearchsubj)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtIdnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtMidname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBack)
                    .addComponent(jbtnSavesubj))
                .addGap(31, 31, 31))
        );

        jSeparator1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQuizActionPerformed

    private void jtxtIdnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdnumActionPerformed

    private void jbtnSearchsubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchsubjActionPerformed
        String idsearch = jtxtSearch.getText();
       
        try{
            String host = "jdbc:mysql://localhost:3306/student_grading_system";
            String user = "root";
            String pass = "";
            con = DriverManager.getConnection(host,user,pass);
            pst = con.prepareStatement("Select * from gradingsystem where idnum=?");
            pst.setString(1, idsearch);
            rs = pst.executeQuery();
            while(rs.next()){
                
                jtxtIdnum.setText(rs.getString("idnum"));
                jtxtIdnum.setEditable(false);
                jtxtFirstname.setText(rs.getString("firstname"));
                jtxtFirstname.setEditable(false);
                jtxtLastname.setText(rs.getString("lastname"));
                jtxtLastname.setEditable(false);
                jtxtMidname.setText(rs.getString("middlename"));
                jtxtMidname.setEditable(false);
            }
            
//            JOptionPane.showMessageDialog(null, "Record not Found !");
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
                
                
    }//GEN-LAST:event_jbtnSearchsubjActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        new JfrmSystem().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnSavesubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSavesubjActionPerformed
        try{
            String id = jtxtIdnum.getText();
            int newID = Integer.parseInt(id);
            jtxtIdnum.setEditable(false);
            String lastname = jtxtLastname.getText();
            jtxtLastname.setEditable(false);
//            String firstname = jtxtFirstname.getText();
//            String middlename = jtxtMid.getText();
            String subject = jcboxSubj.getSelectedItem().toString();
            //computation
            String Attend = jtxtAtt.getText();
            int newAttend = Integer.parseInt(Attend);
            String Part = jtxtPart.getText();
            int newPart = Integer.parseInt(Part);
            String Proj = jtxtProj.getText();
            int newProj = Integer.parseInt(Proj);
            String Quiz = jtxtQuiz.getText();
            int newQuiz = Integer.parseInt(Quiz);
            String Attit = jtxtAttit.getText();
            int newAttit = Integer.parseInt(Attit);
            String finalex = jtxtFinal.getText();
            int finalexam = Integer.parseInt(finalex);
            int finalg = (newAttend+newPart+newProj+newQuiz+newAttit+finalexam);
            String finalgrade = String.valueOf(finalg);
            jtxtGrade.setText(finalgrade);
            jtxtGrade.setEditable(false);
            jtxtFirstname.setEditable(false);
            jtxtMidname.setEditable(false);   
            
            String insert = "INSERT INTO subjects VALUES('"+newID+"','"+lastname+"','"+subject+"','"+newAttend+"','"+newQuiz+
                    "','"+newPart+"','"+newProj+"','"+finalexam+"','"+newAttit+"','"+finalgrade+"')";
            stmt.executeUpdate(insert);
            
            JOptionPane.showMessageDialog(null, "Subject is now recorded!");
                jtxtLastname.setText("");
                jtxtIdnum.setText("");
                jtxtAtt.setText("");
                jtxtPart.setText("");
                jtxtProj.setText("");
                jtxtQuiz.setText("");
                jtxtAttit.setText("");
                jtxtFinal.setText("");
                jtxtGrade.setText("");   
                jtxtFirstname.setText("");
                jtxtMidname.setText("");
                
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_jbtnSavesubjActionPerformed

    private void jtxtAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAttActionPerformed

    private void jcboxSubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxSubjActionPerformed
        
    }//GEN-LAST:event_jcboxSubjActionPerformed

    private void jtxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchActionPerformed

    private void jtxtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastnameActionPerformed

    private void jtxtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGradeActionPerformed

    private void jbtnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnScoreActionPerformed
        String Attend = jtxtAtt.getText();
            int newAttend = Integer.parseInt(Attend);
            String Part = jtxtPart.getText();
            int newPart = Integer.parseInt(Part);
            String Proj = jtxtProj.getText();
            int newProj = Integer.parseInt(Proj);
            String Quiz = jtxtQuiz.getText();
            int newQuiz = Integer.parseInt(Quiz);
            String Attit = jtxtAttit.getText();
            int newAttit = Integer.parseInt(Attit);
            String finalex = jtxtFinal.getText();
            int finalexam = Integer.parseInt(finalex);
//            String finalg = jtxtGrade.getText();
//            int finalgg = Integer.parseInt(finalg);
            int finalg = (newAttend+newPart+newProj+newQuiz+newAttit+finalexam);
            String finalgrade = String.valueOf(finalg);
            jtxtGrade.setText(finalgrade);
            jtxtGrade.setEditable(false);
           
    }//GEN-LAST:event_jbtnScoreActionPerformed

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
                jtxtLastname.setText("");
                jtxtIdnum.setText("");
                jtxtAtt.setText("");
                jtxtPart.setText("");
                jtxtProj.setText("");
                jtxtQuiz.setText("");
                jtxtAttit.setText("");
                jtxtFinal.setText("");
                jtxtGrade.setText("");   
                jtxtFirstname.setText("");
                jtxtMidname.setText("");
    }//GEN-LAST:event_jbtnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnSavesubj;
    private javax.swing.JButton jbtnScore;
    private javax.swing.JButton jbtnSearchsubj;
    private javax.swing.JComboBox jcboxSubj;
    private javax.swing.JTextField jtxtAtt;
    private javax.swing.JTextField jtxtAttit;
    private javax.swing.JTextField jtxtFinal;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGrade;
    private javax.swing.JTextField jtxtIdnum;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtMidname;
    private javax.swing.JTextField jtxtPart;
    private javax.swing.JTextField jtxtProj;
    private javax.swing.JTextField jtxtQuiz;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
}
